# Generated by Django 5.1.6 on 2025-04-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CountryPopulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                ("iso3", models.CharField(max_length=3, verbose_name="Код ISO3")),
                ("year", models.IntegerField(verbose_name="Год")),
                ("population", models.BigIntegerField(verbose_name="Население")),
                (
                    "population_growth",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Прирост населения"
                    ),
                ),
                (
                    "growth_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Темп роста (%)",
                    ),
                ),
                ("decade", models.CharField(max_length=10, verbose_name="Десятилетие")),
            ],
            options={
                "verbose_name": "Население страны",
                "verbose_name_plural": "Население стран",
                "db_table": "country_population",
                "unique_together": {("country", "year")},
            },
        ),
    ]
